name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'

      - name: Go to Flutter project and get packages
        run: |
          cd hok_regl_full_ready/hok_regl_android_fixed
          flutter pub get

      - name: Analyze project (ignore warnings)
        run: |
          cd hok_regl_full_ready/hok_regl_android_fixed
          flutter analyze || true

      - name: Build release APK
        run: |
          cd hok_regl_full_ready/hok_regl_android_fixed
          flutter build apk --release

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: hok_regl_full_ready/hok_regl_android_fixed/build/app/outputs/flutter-apk/app-release.apk
