name: Build Flutter APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter 1.22.6 (supports v1 embedding)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '1.22.6'

      - name: Get dependencies
        run: flutter pub get
        working-directory: hok_regl_full_ready/hok_regl_android_fixed

      - name: Build release APK
        run: flutter build apk --release
        working-directory: hok_regl_full_ready/hok_regl_android_fixed

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: hok_regl_full_ready/hok_regl_android_fixed/build/app/outputs/flutter-apk/app-release.apk
